" enable syntax highlight
syntax on

" enable file type detection
filetype on
filetype plugin on

" set line number relatively to cursor position
set relativenumber

" display cursor column
set cursorcolumn

" display cursor line
set cursorline

" set tab to 4 spaces
set tabstop=4

" set autoindent to 4 spaces
set shiftwidth=4

" enable autoindent
set autoindent
set smartindent

" set highlight when searching
set incsearch

" load colorscheme
packadd! gruvbox-material
colorscheme gruvbox-material

" set mapping for NERDTree
map  :NERDTreeToggle

" set maaping for switching tabs
map  :tabnext
" set lightline for status bar
set laststatus=2
set noshowmode
